version: "3.3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
      - /data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090"

  #alertmanager:
  #  image: prom/alertmanager
  #  container_name: alertmanager
  #  volumes:
  #    - ./data/alertmanager:/etc/alertmanager
  #  command:
  #    - '--config.file=/etc/alertmanager/config.yml'
  #    - '--storage.path=/alertmanager'
  #  restart: unless-stopped
  #  expose:
  #    - "9093"
  
  grafana:
    image: grafana/grafana:latest
    depends_on: 
      - prometheus
      - renderer
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - /data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=CH4NG3M3
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=monitoramento.multiprova.ufrn.br
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=monitoramento.multiprova.ufrn.br
      - GF_SMTP_USER=suporte
      - GF_SMTP_PASSWORD=CH4NG3M3
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    ports:
      - "3000"

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'

  nginx:
    depends_on:
      - grafana
    container_name: nginx
    image: nginx:1.18.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/auth:/etc/nginx/.htpasswd
      - ./nginx/monitoramento.multiprova.ufrn.br.crt:/etc/certificados/monitoramento.multiprova.ufrn.br.crt
      - ./nginx/monitoramento.multiprova.ufrn.br.key:/etc/certificados/monitoramento.multiprova.ufrn.br.key
    ports:
      - "80:80"
      - "443:443"
      - "9090:9090"

volumes:
  grafana-storage:
