global:
  scrape_interval:     10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'mp-cluster'


# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'cluster-dev'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 10s
   
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
         - targets: ['10.3.227.29:30000']

  - job_name: 'd2s-node-exporter'
    static_configs:
         - targets: ['10.3.227.29:9100', '10.3.227.26:9100', '10.3.227.27:9100', '10.3.227.28:9100']

  - job_name: 'd2s-cadvisor'
    static_configs:
         - targets: ['10.3.227.29:8080', '10.3.227.26:8080', '10.3.227.27:8080', '10.3.227.28:8080']

  - job_name: 'prod-node-exporter'
    static_configs:
         - targets: ['10.3.224.209:9100', '10.3.224.212:9100', '10.3.224.213:9100', '10.3.224.60:9100']

  #- job_name: 'prod-cadvisor'
   # static_configs:
    #     - targets: ['10.3.224.209:8080', '10.3.224.212:8080', '10.3.224.213:8080', '10.3.224.60:8080']



  - job_name: 'rabbitMQ-d2s'
    static_configs:
         - targets: ['10.3.227.27:32093']

  - job_name: 'monitor-node-exporter'
    static_configs:
         - targets: ['10.3.227.6:9100']

  - job_name: 'monitor-cadvisor'
    static_configs:
         - targets: ['10.3.227.6:8080']


  - job_name: 'logs-node-exporter'
    static_configs:
         - targets: ['10.3.227.5:9100']


  - job_name: 'logs-cadvisor'
    static_configs:
         - targets: ['10.3.227.5:8080']


  - job_name: 'broker-prod-node-exporter'
    static_configs:
         - targets: ['10.3.224.115:9100']

  #- job_name: 'broker-prod-cadvisor'
   # static_configs:
    #     - targets: ['10.3.224.115:8080']




  - job_name: 'bd-node-exporter'
    static_configs:
         - targets: ['10.3.224.210:9100']

  #- job_name: 'bd-cadvisor'
   # static_configs:
    #     - targets: ['10.3.224.210:8080']

  - job_name: 'teste-bd-node-exporter'
    static_configs:
         - targets: ['10.3.227.30:9100']

  - job_name: 'teste-bd-cadvisor'
    static_configs:
         - targets: ['10.3.227.30:8080']

  - job_name: 'mongodb_exporter'
    static_configs:
         - targets: ['10.3.227.30:9216']
